# Generated by Django 3.1.3 on 2020-11-14 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20201113_1805'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['Category']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='name',
            new_name='title',
        ),
    ]
