# Generated by Django 3.1.3 on 2020-11-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_auto_20201114_0945'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='Location',
            new_name='location',
        ),
    ]
