# Generated by Django 3.1.3 on 2020-11-15 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0008_auto_20201114_2227'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image_image']},
        ),
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='image_image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
