# Generated by Django 3.1.3 on 2020-11-15 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0009_auto_20201115_0723'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['image']},
        ),
        migrations.RenameField(
            model_name='image',
            old_name='image_image',
            new_name='image',
        ),
    ]
